name: Quality

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHON_VERSION: '3.12'

jobs:
  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-python-uv
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        git-repos-token: ${{ secrets.GH_REPOS_READ_TOKEN }}
    - name: Run pre-commit
      run: uv run --locked --extra dev pre-commit run --all-files --show-diff-on-failure

  type:
    name: Type checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - uses: ./.github/actions/setup-python-uv
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        git-repos-token: ${{ secrets.GH_REPOS_READ_TOKEN }}
    - name: Run type checks
      run: uv run --locked --extra dev tox run -e type
